### ISSUE TITLE
Custom serialization for byte[]

### ISSUE THREAD

**Issue by uurha** [MS-LIMA/PhotonSerializer#2]
Hello, thanks for creating this serializer. It's very helpful, could you please help me with extending your serializer. I want to add serializing for byte[], but it gives me error about lenght of byte array, but I done this same as int[].

```c#
public static void Serialize(byte value, ref byte[] bytes)
{
    byte[] _bytes = BitConverter.GetBytes(value);
    if (BitConverter.IsLittleEndian)
        Array.Reverse(_bytes);

    JoinBytes(ref bytes, _bytes);
}
        
public static void Serialize(byte[] values, ref byte[] bytes)
{
    int length = values == null ? 0 : values.Length;
    if (length > 0)
    {
        Serialize(length, ref bytes);
        for (int i = 0; i < values.Length; i++)
        {
            Serialize(values[i], ref bytes);
        }
    }
    else
    {
        Serialize(0, ref bytes);
    }
}

public static byte DeserializeByte(byte[] bytes, ref int offset)
{
    byte[] _bytes = new byte[4];
    Array.Copy(bytes, offset, _bytes, 0, 4);

    if (BitConverter.IsLittleEndian)
        Array.Reverse(_bytes);

    offset += 4;
    return (byte)BitConverter.ToInt16(_bytes, 0);

    // int, float, bool vecot3, ve2 ,qua, string
}

public static byte[] DeserializeByteArray(byte[] bytes, ref int offset)
{
    int length = DeserializeInt(bytes, ref offset);
    if (length > 0)
    {
        byte[] array = new byte[length];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = DeserializeByte(bytes, ref offset);
        }

        return array;
    }

    return new byte[0];
}
```

**Comment by MS-LIMA** [comment]
Hi, thank you for your interest in my archive.

In fact, BitConverter serializes other data types into bytes, therefore, using BitConverter is not necessary to serialize bytes!

Try this below.

===================

public static void Serialize(byte value, ref byte[] bytes)
        {
            byte[] _bytes = new byte[] {value};
            bytes = bytes.Concat(_bytes).ToArray();
        }

public static byte DeserializeByte(byte[] bytes, ref int offset)
{
    byte _byte = bytes[offset];

    offset += 1;
    return _byte;
}


public static byte[] DeserializeByteArray(byte[] bytes, ref int offset)
{
    int length = DeserializeInt(bytes, ref offset);
    if (length > 0)
    {
        byte[] array = new byte[length];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = DeserializeByte(bytes, ref offset);
        }

        return array;
    }

    return new byte[0];
}

**Comment by uurha** [comment]
Thanks. I'll come then I'll finish tests)

**Comment by uurha** [comment]
Well tested and working good, thanks for your help) Will I close the issue?

**Comment by MS-LIMA** [comment]
Yes, please.
Thanks for your advice, I'll update it to my serializer later on.

**Comment by uurha** [comment]
> Yes, please.
> Thanks for your advice, I'll update it to my serializer later on.

I can make pull request from fork. Is that will be good?)

**Comment by MS-LIMA** [comment]
> I can make pull request from fork. Is that will be good?)

Sure, :)
