### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by uurha** [MS-LIMA/PhotonSerializer#4]
Good day, do you mind if I'll prepare your asset for package released on https://openupm.com? I wanna create Photon RaiseEvent Bus system, and I wanna add dependency onto your package to keep you as creator of this serializer.

**Comment by MS-LIMA** [comment]
Hi, it's been a while. Sure, No problem!

**Comment by uurha** [comment]
Hi again) I almost finish with preparing for UPM but github action what preparing repo for UPM requires to set repo secrets.

- [ ] ADMIN_NAME
- [ ]  ADMIN_MAIL

![image](https://user-images.githubusercontent.com/22265817/204329999-09d6f297-9695-4981-b64e-a4f04a453941.png)
![image](https://user-images.githubusercontent.com/22265817/204329985-1f570dc5-2e02-47df-81e2-8b5a8b2a0409.png)

Or I can do this all by myself if you will add me as collaborator to this repo.
Thanks)

**Comment by uurha** [comment]
Hi again, can you give me please admin access because right now I cant set secrets to this repo 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#changing-permissions-for-a-team-or-person

**Comment by uurha** [comment]
> Hi again) I almost finish with preparing for UPM but github action what preparing repo for UPM requires to set repo secrets.
> 
> * [x]  ADMIN_NAME
> * [x]   ADMIN_MAIL

GitHub action saying that there no secrets like this, can you double check please?

**Comment by arcueid-dev** [comment]
Hi) I publish your plugin) thank you for giving me possibility to publish it. Here [link](https://openupm.com/packages/com.ms-lima.photonserializer/)

**Comment by arcueid-dev** [comment]
Published to OpenUPM
